### ISSUE TITLE
initialisation documentation

### ISSUE THREAD

**Issue by alavenant** [ign-gpao/.github#1]
- [x] Api
- [x] Client
- [x] Monitor
- [x] Database
- [x] Builder
- [x] Docker
- [x] Client

**Comment by ijeuffrard** [comment]
ajouter un lien dans le menu gauche vers la documentation d'installation du client

**Comment by ijeuffrard** [comment]
ajouter une note dans INSTALL.md pour préciser qu'il est préférable d'utiliser powerShell sous windows
