### ISSUE TITLE
Documenter les variables d'environnement

### ISSUE THREAD

**Issue by IGNBPesty** [ign-gpao/.github#2]
On a ajouté quelques variables d'environnement pour le monitor et l'API, on peut éventuellement les lister sur la page d'accueil du projet avec un peu d'explication.

Pour l'API : 
| Variable          | Obligatoire | Valeur par défaut | Commentaire |
|--------------------|----------------|-------------------------|--------------------|
| API_PORT      |  Non  |  8080 | Port de l'API  |
| SERVER_HOSTNAME      |  Non  |  localhost |  Nom de la machine qui héberge l'API  |
| PGHOST       |  Oui   |    | Nom de la machine qui héberge la base de données  |
| PGPORT       |  Oui   |    |  Port pour la base de données |
| PGUSER       |  Oui   |    |  User de connexion Postgresql |
| PGPASSWORD  | Oui    |    |  Password de connexion Postgresql |
| PGDATABASE  | Oui    |    |  Nom de la base GPAO |

Pour le monitor :
| Variable          | Obligatoire | Valeur par défaut | Commentaire |
|--------------------|----------------|-------------------------|--------------------|
| SERVER_HOSTNAME |  Non | localhost   | Nom de la machine qui héberge le monitor |
| URL_MONITOR | Non | localhost | l'URL du monitor |
| MONITOR_PORT | Non | 8000  | Port du monitor  |
| URL_API  |  Non  | localhost  |  Nom de la machine qui héberge l'API|
| API_PORT |  Non  |  8080 | Port de l'API vu par le monitor |
| BASE_URL |  Non  |  '' | Url de base du site (utile dans le cas où un alias a été créé pour le site et que cela diffère du nom de machine)  |

Pour le client : 
| Variable          | Obligatoire | Valeur par défaut | Commentaire |
|--------------------|----------------|-------------------------|--------------------|
| API_PROTOCOL | Non | http | Protocole utilisé par le client pour se connecter à l'API |
| URL_API  | Non |  localhost  |  Nom du serveur hébergeant l'API |
| API_PORT | Non |  8080  |  Port de l'API vu par le client  |
| GPAO_MIN_AVAILABLE_SPACE | Non | 5 (Go) | Espace disque minimal pour que le client démarre |

**Comment by ijeuffrard** [comment]
Merci pour ces tableaux ! Je les ai rajoutés à la doc qui a d'ailleurs pas mal avancé (la page d'accueil mais surtout les README de chaque "brique" gpao)

**Comment by IGNBPesty** [comment]
Nice ^^
